<Project Sdk="Microsoft.NET.Sdk">
  <Import Project="../common.targets" />
  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <OutputType>Library</OutputType>
    <OutputPath>..\bin\$(Configuration)\lib\</OutputPath>
    <Description>Base library for Endless Online development</Description>
    <EnforceCodeStyleInBuild>true</EnforceCodeStyleInBuild>
  </PropertyGroup>
  <PropertyGroup Condition="$([MSBuild]::IsOSPlatform('Linux'))">
    <DefineConstants>$(DefineConstants);LINUX</DefineConstants>
  </PropertyGroup>
  <PropertyGroup Condition="'$(Configuration.Contains(`Debug`))'">
    <DebugSymbols>true</DebugSymbols>
  </PropertyGroup>
</Project>
